# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:

  integration-tests:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    command:
      [
        "./scripts/start-tests.sh",
      ]
    networks:
      - instrumentation

  lint-formatter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-formatter-lint.sh"]
    networks:
      - instrumentation

  broker-rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 61613:61613
      - 15672:15672
    volumes:
      - ./tests/resources/custom-rabbitmq-conf:/etc/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - instrumentation

networks:
  instrumentation: